services:
  nginx-service:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  php-service:
    build:
      dockerfile: ./php/Dockerfile
      target: app
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
  postgres-service:
    image: postgres:16
    volumes:
      - postgresdata:/var/lib/postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
  pgadmin-service:
    image: elestio/pgadmin:REL-8_3
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 9090
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - 9090:8080
  cache-service:
    image: redis:7.2.4

volumes:
  postgresdata:
